on:
  deployment

jobs:
  if_deployment_on_vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Discord Webhook
        uses : tsickert/discord-webhook@v5.3.0
        with:
          webhook-url : ${{ secrets.DISCORD_WEBHOOK_URL }}
          raw-data : webhook.json
